# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-31 00:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configuration_management_tools', '0002_auto_20170731_0022'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='smslibgateways',
            options={'managed': False, 'verbose_name': 'Gateway'},
        ),
        migrations.AlterModelOptions(
            name='smslibnumberroutes',
            options={'managed': False, 'verbose_name': 'Route'},
        ),
    ]
