# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-31 01:34
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configuration_management_tools', '0003_auto_20170731_0023'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(default='')),
                ('is_active', models.BooleanField(default=False)),
                ('start', models.TimeField(default=datetime.time(8, 0))),
                ('end', models.TimeField(default=datetime.time(20, 0))),
            ],
        ),
        migrations.CreateModel(
            name='Campaign_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=16)),
                ('text', models.CharField(max_length=1024)),
                ('campaign_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configuration_management_tools.Campaign')),
            ],
        ),
    ]
